### ISSUE TITLE
When trying to access API of _Simonwolf it shows Error 500

### ISSUE THREAD

**Issue by simonwolfsimonwolf** [Senither/hypixel-skyblock-facade#10]
Example here in a profile viewer:
https://sky.shiiyu.moe/stats/_Simonwolf

**Comment by Senither** [comment]
The issue seems to stem directly from Hypixels API since both sky.shiiyu.moe and Hypixels API itself are throwing a 500 error when attempting to load SkyBlock data for `_Simonwolf`, here is an example of the response returned directly by Hypixel.

![Hypixel API call for _Simonwolf](https://media.senither.com/i/AWillingPremiumStranger)

I can't really do anything about it on my end, but you can try report the issue on Hypixels github repo at [HypixelDev/PublicAPI](https://github.com/HypixelDev/PublicAPI).
