### ISSUE TITLE
API doesn't accept non-dashed UUIDs

### ISSUE THREAD

**Issue by plun1331** [Senither/hypixel-skyblock-facade#2]
As the title states, the API does not accept non-dashed UUIDs.

![image](https://user-images.githubusercontent.com/49261529/109232825-c08cc380-777d-11eb-80b6-64d81d94397b.png)

![image](https://user-images.githubusercontent.com/49261529/109232909-dd28fb80-777d-11eb-8bae-cfe02232a843.png)

On another note, the documentation states that the API should return a 404 in this case, however, it returns a 400 instead, which I have fixed in PR #1, I think.

**Comment by Senither** [comment]
The API defines a UUID by [RFC 4122](https://tools.ietf.org/html/rfc4122#page-4) (section 3, page 4), which does not consider UUIDs without dashes as valid, the API not supporting non-dashed UUIDs is completely intentional, and the 400 error code is therefore also as expected since an invalid UUID was provided.

I could add some more specific documentation on what exactly the UUID must look like, however, there are no real plans on supporting non-dashed UUIDs in the API for now.
